package defpackage;

import java.util.List;
import java.util.Map;

/* JADX INFO: compiled from: r8-map-id-6d4a6fea4a678d318bae670e8b98ae0a8798384e7d56dd89fbb5b2340ff4b0eb */
/* JADX INFO: loaded from: D:\Tool\vbook-ext\.tools\vbook-dex\classes3.dex */
public final /* synthetic */ class b82 implements kb4 {
    public final /* synthetic */ int a;
    public final /* synthetic */ b92 b;

    public /* synthetic */ b82(b92 b92Var, int i) {
        this.a = i;
        switch (i) {
            case 1:
                z82 z82Var = z82.a;
                break;
            case 2:
                a92 a92Var = a92.a;
                break;
            case 3:
                v82 v82Var = v82.a;
                break;
            case 4:
                x82 x82Var = x82.a;
                break;
            case 5:
                u82 u82Var = u82.a;
                break;
            case 6:
                q82 q82Var = q82.a;
                break;
            case 7:
                t82 t82Var = t82.a;
                break;
            case 8:
                y82 y82Var = y82.a;
                break;
            case 9:
                break;
            case 10:
                r82 r82Var = r82.a;
                break;
            case 11:
                w82 w82Var = w82.a;
                break;
            case 12:
                s82 s82Var = s82.a;
                break;
            default:
                p82 p82Var = p82.a;
                break;
        }
        this.b = b92Var;
    }

    private final Object a(Object obj) {
        x82 x82Var = x82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        bv4 bv4Var = (bv4) this.b.c;
        bv4Var.getClass();
        wfc wfcVar = wfc.t;
        String strD = reVar.d(1);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        bv4Var.getClass();
        Object objN = ky0.n(reVar, 2, wfcVar);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objM, objN, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    private final Object b(Object obj) {
        u82 u82Var = u82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        b92 b92Var = this.b;
        ((bv4) b92Var.c).getClass();
        wfc wfcVar = wfc.t;
        Object objN = ky0.n(reVar, 1, wfcVar);
        ((bv4) b92Var.c).getClass();
        String strD = reVar.d(2);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objN, objM, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    private final Object d(Object obj) {
        q82 q82Var = q82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        bv4 bv4Var = (bv4) this.b.c;
        bv4Var.getClass();
        wfc wfcVar = wfc.t;
        String strD = reVar.d(1);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        bv4Var.getClass();
        Object objN = ky0.n(reVar, 2, wfcVar);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objM, objN, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    private final Object f(Object obj) {
        t82 t82Var = t82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        b92 b92Var = this.b;
        ((bv4) b92Var.c).getClass();
        wfc wfcVar = wfc.t;
        Object objN = ky0.n(reVar, 1, wfcVar);
        ((bv4) b92Var.c).getClass();
        String strD = reVar.d(2);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objN, objM, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    private final Object i(Object obj) {
        y82 y82Var = y82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        bv4 bv4Var = (bv4) this.b.c;
        bv4Var.getClass();
        wfc wfcVar = wfc.t;
        String strD = reVar.d(1);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        bv4Var.getClass();
        Object objN = ky0.n(reVar, 2, wfcVar);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objM, objN, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    private final Object l(Object obj) {
        r82 r82Var = r82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        bv4 bv4Var = (bv4) this.b.c;
        bv4Var.getClass();
        wfc wfcVar = wfc.t;
        String strD = reVar.d(1);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        bv4Var.getClass();
        Object objN = ky0.n(reVar, 2, wfcVar);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objM, objN, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    private final Object m(Object obj) {
        w82 w82Var = w82.a;
        re reVar = (re) obj;
        String strO = ky0.o(reVar, 0);
        bv4 bv4Var = (bv4) this.b.c;
        bv4Var.getClass();
        wfc wfcVar = wfc.t;
        String strD = reVar.d(1);
        strD.getClass();
        Object objM = wfcVar.m(strD);
        bv4Var.getClass();
        Object objN = ky0.n(reVar, 2, wfcVar);
        String strD2 = reVar.d(3);
        Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
        Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
        fu6 fu6Var = fu6.C;
        String strD3 = reVar.d(6);
        strD3.getClass();
        Object objW = fu6Var.w(strD3);
        String strD4 = reVar.d(7);
        String strQ = ky0.q(strD4, reVar, 8);
        String strD5 = reVar.d(9);
        String strQ2 = ky0.q(strD5, reVar, 10);
        String strD6 = reVar.d(11);
        Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
        Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
        Object objN2 = ky0.n(reVar, 14, wfcVar);
        Boolean boolA = reVar.a(15);
        boolA.getClass();
        String strD7 = reVar.d(16);
        strD7.getClass();
        String strD8 = reVar.d(17);
        Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
        Double dB = reVar.b();
        dB.getClass();
        Long lC = reVar.c(20);
        lC.getClass();
        Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
        Long lC2 = reVar.c(21);
        Long lM = ky0.m(lC2, reVar, 22);
        Boolean boolA2 = reVar.a(23);
        Boolean boolL = ky0.l(boolA2, reVar, 24);
        Boolean boolA3 = reVar.a(25);
        Boolean boolL2 = ky0.l(boolA3, reVar, 26);
        Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
        Object objN3 = ky0.n(reVar, 28, wfcVar);
        Object objN4 = ky0.n(reVar, 29, wfcVar);
        Long lC3 = reVar.c(30);
        Long lM2 = ky0.m(lC3, reVar, 31);
        Long lC4 = reVar.c(32);
        Long lM3 = ky0.m(lC4, reVar, 33);
        Long lC5 = reVar.c(34);
        lC5.getClass();
        Object[] objArr = {strO, objM, objN, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
        if (objArr.length != 35) {
            gp.l("Expected 35 arguments");
            return null;
        }
        String str = (String) objArr[0];
        Map map = (Map) objArr[1];
        Map map2 = (Map) objArr[2];
        String str2 = (String) objArr[3];
        int iIntValue = ((Number) objArr[4]).intValue();
        int iIntValue2 = ((Number) objArr[5]).intValue();
        List list = (List) objArr[6];
        String str3 = (String) objArr[7];
        String str4 = (String) objArr[8];
        String str5 = (String) objArr[9];
        String str6 = (String) objArr[10];
        String str7 = (String) objArr[11];
        int iIntValue3 = ((Number) objArr[12]).intValue();
        int iIntValue4 = ((Number) objArr[13]).intValue();
        Map map3 = (Map) objArr[14];
        boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
        String str8 = (String) objArr[16];
        String str9 = (String) objArr[17];
        int iIntValue5 = ((Number) objArr[18]).intValue();
        double dDoubleValue = ((Number) objArr[19]).doubleValue();
        int iIntValue6 = ((Number) objArr[20]).intValue();
        long jLongValue = ((Number) objArr[21]).longValue();
        long jLongValue2 = ((Number) objArr[22]).longValue();
        boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
        boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
        boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
        boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
        int iIntValue7 = ((Number) objArr[27]).intValue();
        Map map4 = (Map) objArr[28];
        Map map5 = (Map) objArr[29];
        long jLongValue3 = ((Number) objArr[30]).longValue();
        long jLongValue4 = ((Number) objArr[31]).longValue();
        long jLongValue5 = ((Number) objArr[32]).longValue();
        long jLongValue6 = ((Number) objArr[33]).longValue();
        long jLongValue7 = ((Number) objArr[34]).longValue();
        str.getClass();
        map.getClass();
        map2.getClass();
        str2.getClass();
        list.getClass();
        str3.getClass();
        str4.getClass();
        str5.getClass();
        str6.getClass();
        map3.getClass();
        str8.getClass();
        str9.getClass();
        map4.getClass();
        map5.getClass();
        return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
    }

    @Override // defpackage.kb4
    public final Object invoke(Object obj) {
        switch (this.a) {
            case 0:
                p82 p82Var = p82.a;
                re reVar = (re) obj;
                String strO = ky0.o(reVar, 0);
                b92 b92Var = this.b;
                ((bv4) b92Var.c).getClass();
                wfc wfcVar = wfc.t;
                Object objN = ky0.n(reVar, 1, wfcVar);
                ((bv4) b92Var.c).getClass();
                String strD = reVar.d(2);
                strD.getClass();
                Object objM = wfcVar.m(strD);
                String strD2 = reVar.d(3);
                Integer numValueOf = Integer.valueOf((int) ky0.d(strD2, reVar, 4));
                Integer numValueOf2 = Integer.valueOf((int) ky0.c(reVar, 5));
                fu6 fu6Var = fu6.C;
                String strD3 = reVar.d(6);
                strD3.getClass();
                Object objW = fu6Var.w(strD3);
                String strD4 = reVar.d(7);
                String strQ = ky0.q(strD4, reVar, 8);
                String strD5 = reVar.d(9);
                String strQ2 = ky0.q(strD5, reVar, 10);
                String strD6 = reVar.d(11);
                Integer numValueOf3 = Integer.valueOf((int) ky0.c(reVar, 12));
                Integer numValueOf4 = Integer.valueOf((int) ky0.c(reVar, 13));
                Object objN2 = ky0.n(reVar, 14, wfcVar);
                Boolean boolA = reVar.a(15);
                boolA.getClass();
                String strD7 = reVar.d(16);
                strD7.getClass();
                String strD8 = reVar.d(17);
                Integer numValueOf5 = Integer.valueOf((int) ky0.d(strD8, reVar, 18));
                Double dB = reVar.b();
                dB.getClass();
                Long lC = reVar.c(20);
                lC.getClass();
                Integer numValueOf6 = Integer.valueOf((int) lC.longValue());
                Long lC2 = reVar.c(21);
                Long lM = ky0.m(lC2, reVar, 22);
                Boolean boolA2 = reVar.a(23);
                Boolean boolL = ky0.l(boolA2, reVar, 24);
                Boolean boolA3 = reVar.a(25);
                Boolean boolL2 = ky0.l(boolA3, reVar, 26);
                Integer numValueOf7 = Integer.valueOf((int) ky0.c(reVar, 27));
                Object objN3 = ky0.n(reVar, 28, wfcVar);
                Object objN4 = ky0.n(reVar, 29, wfcVar);
                Long lC3 = reVar.c(30);
                Long lM2 = ky0.m(lC3, reVar, 31);
                Long lC4 = reVar.c(32);
                Long lM3 = ky0.m(lC4, reVar, 33);
                Long lC5 = reVar.c(34);
                lC5.getClass();
                Object[] objArr = {strO, objN, objM, strD2, numValueOf, numValueOf2, objW, strD4, strQ, strD5, strQ2, strD6, numValueOf3, numValueOf4, objN2, boolA, strD7, strD8, numValueOf5, dB, numValueOf6, lC2, lM, boolA2, boolL, boolA3, boolL2, numValueOf7, objN3, objN4, lC3, lM2, lC4, lM3, lC5};
                if (objArr.length != 35) {
                    gp.l("Expected 35 arguments");
                    return null;
                }
                String str = (String) objArr[0];
                Map map = (Map) objArr[1];
                Map map2 = (Map) objArr[2];
                String str2 = (String) objArr[3];
                int iIntValue = ((Number) objArr[4]).intValue();
                int iIntValue2 = ((Number) objArr[5]).intValue();
                List list = (List) objArr[6];
                String str3 = (String) objArr[7];
                String str4 = (String) objArr[8];
                String str5 = (String) objArr[9];
                String str6 = (String) objArr[10];
                String str7 = (String) objArr[11];
                int iIntValue3 = ((Number) objArr[12]).intValue();
                int iIntValue4 = ((Number) objArr[13]).intValue();
                Map map3 = (Map) objArr[14];
                boolean zBooleanValue = ((Boolean) objArr[15]).booleanValue();
                String str8 = (String) objArr[16];
                String str9 = (String) objArr[17];
                int iIntValue5 = ((Number) objArr[18]).intValue();
                double dDoubleValue = ((Number) objArr[19]).doubleValue();
                int iIntValue6 = ((Number) objArr[20]).intValue();
                long jLongValue = ((Number) objArr[21]).longValue();
                long jLongValue2 = ((Number) objArr[22]).longValue();
                boolean zBooleanValue2 = ((Boolean) objArr[23]).booleanValue();
                boolean zBooleanValue3 = ((Boolean) objArr[24]).booleanValue();
                boolean zBooleanValue4 = ((Boolean) objArr[25]).booleanValue();
                boolean zBooleanValue5 = ((Boolean) objArr[26]).booleanValue();
                int iIntValue7 = ((Number) objArr[27]).intValue();
                Map map4 = (Map) objArr[28];
                Map map5 = (Map) objArr[29];
                long jLongValue3 = ((Number) objArr[30]).longValue();
                long jLongValue4 = ((Number) objArr[31]).longValue();
                long jLongValue5 = ((Number) objArr[32]).longValue();
                long jLongValue6 = ((Number) objArr[33]).longValue();
                long jLongValue7 = ((Number) objArr[34]).longValue();
                str.getClass();
                map.getClass();
                map2.getClass();
                str2.getClass();
                list.getClass();
                str3.getClass();
                str4.getClass();
                str5.getClass();
                str6.getClass();
                map3.getClass();
                str8.getClass();
                str9.getClass();
                map4.getClass();
                map5.getClass();
                return new a82(dDoubleValue, iIntValue, iIntValue2, iIntValue3, iIntValue4, iIntValue5, iIntValue6, iIntValue7, jLongValue, jLongValue2, jLongValue3, jLongValue4, jLongValue5, jLongValue6, jLongValue7, str, str2, str3, str4, str5, str6, str7, str8, str9, list, map, map2, map3, map4, map5, zBooleanValue, zBooleanValue2, zBooleanValue3, zBooleanValue4, zBooleanValue5);
            case 1:
                z82 z82Var = z82.a;
                re reVar2 = (re) obj;
                String strO2 = ky0.o(reVar2, 0);
                b92 b92Var2 = this.b;
                ((bv4) b92Var2.c).getClass();
                wfc wfcVar2 = wfc.t;
                Object objN5 = ky0.n(reVar2, 1, wfcVar2);
                ((bv4) b92Var2.c).getClass();
                String strD9 = reVar2.d(2);
                strD9.getClass();
                Object objM2 = wfcVar2.m(strD9);
                String strD10 = reVar2.d(3);
                Integer numValueOf8 = Integer.valueOf((int) ky0.d(strD10, reVar2, 4));
                Integer numValueOf9 = Integer.valueOf((int) ky0.c(reVar2, 5));
                fu6 fu6Var2 = fu6.C;
                String strD11 = reVar2.d(6);
                strD11.getClass();
                Object objW2 = fu6Var2.w(strD11);
                String strD12 = reVar2.d(7);
                String strQ3 = ky0.q(strD12, reVar2, 8);
                String strD13 = reVar2.d(9);
                String strQ4 = ky0.q(strD13, reVar2, 10);
                String strD14 = reVar2.d(11);
                Integer numValueOf10 = Integer.valueOf((int) ky0.c(reVar2, 12));
                Integer numValueOf11 = Integer.valueOf((int) ky0.c(reVar2, 13));
                Object objN6 = ky0.n(reVar2, 14, wfcVar2);
                Boolean boolA4 = reVar2.a(15);
                boolA4.getClass();
                String strD15 = reVar2.d(16);
                strD15.getClass();
                String strD16 = reVar2.d(17);
                Integer numValueOf12 = Integer.valueOf((int) ky0.d(strD16, reVar2, 18));
                Double dB2 = reVar2.b();
                dB2.getClass();
                Long lC6 = reVar2.c(20);
                lC6.getClass();
                Integer numValueOf13 = Integer.valueOf((int) lC6.longValue());
                Long lC7 = reVar2.c(21);
                Long lM4 = ky0.m(lC7, reVar2, 22);
                Boolean boolA5 = reVar2.a(23);
                Boolean boolL3 = ky0.l(boolA5, reVar2, 24);
                Boolean boolA6 = reVar2.a(25);
                Boolean boolL4 = ky0.l(boolA6, reVar2, 26);
                Integer numValueOf14 = Integer.valueOf((int) ky0.c(reVar2, 27));
                Object objN7 = ky0.n(reVar2, 28, wfcVar2);
                Object objN8 = ky0.n(reVar2, 29, wfcVar2);
                Long lC8 = reVar2.c(30);
                Long lM5 = ky0.m(lC8, reVar2, 31);
                Long lC9 = reVar2.c(32);
                Long lM6 = ky0.m(lC9, reVar2, 33);
                Long lC10 = reVar2.c(34);
                lC10.getClass();
                Object[] objArr2 = {strO2, objN5, objM2, strD10, numValueOf8, numValueOf9, objW2, strD12, strQ3, strD13, strQ4, strD14, numValueOf10, numValueOf11, objN6, boolA4, strD15, strD16, numValueOf12, dB2, numValueOf13, lC7, lM4, boolA5, boolL3, boolA6, boolL4, numValueOf14, objN7, objN8, lC8, lM5, lC9, lM6, lC10};
                if (objArr2.length != 35) {
                    gp.l("Expected 35 arguments");
                    return null;
                }
                String str10 = (String) objArr2[0];
                Map map6 = (Map) objArr2[1];
                Map map7 = (Map) objArr2[2];
                String str11 = (String) objArr2[3];
                int iIntValue8 = ((Number) objArr2[4]).intValue();
                int iIntValue9 = ((Number) objArr2[5]).intValue();
                List list2 = (List) objArr2[6];
                String str12 = (String) objArr2[7];
                String str13 = (String) objArr2[8];
                String str14 = (String) objArr2[9];
                String str15 = (String) objArr2[10];
                String str16 = (String) objArr2[11];
                int iIntValue10 = ((Number) objArr2[12]).intValue();
                int iIntValue11 = ((Number) objArr2[13]).intValue();
                Map map8 = (Map) objArr2[14];
                boolean zBooleanValue6 = ((Boolean) objArr2[15]).booleanValue();
                String str17 = (String) objArr2[16];
                String str18 = (String) objArr2[17];
                int iIntValue12 = ((Number) objArr2[18]).intValue();
                double dDoubleValue2 = ((Number) objArr2[19]).doubleValue();
                int iIntValue13 = ((Number) objArr2[20]).intValue();
                long jLongValue8 = ((Number) objArr2[21]).longValue();
                long jLongValue9 = ((Number) objArr2[22]).longValue();
                boolean zBooleanValue7 = ((Boolean) objArr2[23]).booleanValue();
                boolean zBooleanValue8 = ((Boolean) objArr2[24]).booleanValue();
                boolean zBooleanValue9 = ((Boolean) objArr2[25]).booleanValue();
                boolean zBooleanValue10 = ((Boolean) objArr2[26]).booleanValue();
                int iIntValue14 = ((Number) objArr2[27]).intValue();
                Map map9 = (Map) objArr2[28];
                Map map10 = (Map) objArr2[29];
                long jLongValue10 = ((Number) objArr2[30]).longValue();
                long jLongValue11 = ((Number) objArr2[31]).longValue();
                long jLongValue12 = ((Number) objArr2[32]).longValue();
                long jLongValue13 = ((Number) objArr2[33]).longValue();
                long jLongValue14 = ((Number) objArr2[34]).longValue();
                str10.getClass();
                map6.getClass();
                map7.getClass();
                str11.getClass();
                list2.getClass();
                str12.getClass();
                str13.getClass();
                str14.getClass();
                str15.getClass();
                map8.getClass();
                str17.getClass();
                str18.getClass();
                map9.getClass();
                map10.getClass();
                return new a82(dDoubleValue2, iIntValue8, iIntValue9, iIntValue10, iIntValue11, iIntValue12, iIntValue13, iIntValue14, jLongValue8, jLongValue9, jLongValue10, jLongValue11, jLongValue12, jLongValue13, jLongValue14, str10, str11, str12, str13, str14, str15, str16, str17, str18, list2, map6, map7, map8, map9, map10, zBooleanValue6, zBooleanValue7, zBooleanValue8, zBooleanValue9, zBooleanValue10);
            case 2:
                a92 a92Var = a92.a;
                re reVar3 = (re) obj;
                String strO3 = ky0.o(reVar3, 0);
                b92 b92Var3 = this.b;
                ((bv4) b92Var3.c).getClass();
                wfc wfcVar3 = wfc.t;
                Object objN9 = ky0.n(reVar3, 1, wfcVar3);
                ((bv4) b92Var3.c).getClass();
                String strD17 = reVar3.d(2);
                strD17.getClass();
                Object objM3 = wfcVar3.m(strD17);
                String strD18 = reVar3.d(3);
                Integer numValueOf15 = Integer.valueOf((int) ky0.d(strD18, reVar3, 4));
                Integer numValueOf16 = Integer.valueOf((int) ky0.c(reVar3, 5));
                fu6 fu6Var3 = fu6.C;
                String strD19 = reVar3.d(6);
                strD19.getClass();
                Object objW3 = fu6Var3.w(strD19);
                String strD20 = reVar3.d(7);
                String strQ5 = ky0.q(strD20, reVar3, 8);
                String strD21 = reVar3.d(9);
                String strQ6 = ky0.q(strD21, reVar3, 10);
                String strD22 = reVar3.d(11);
                Integer numValueOf17 = Integer.valueOf((int) ky0.c(reVar3, 12));
                Integer numValueOf18 = Integer.valueOf((int) ky0.c(reVar3, 13));
                Object objN10 = ky0.n(reVar3, 14, wfcVar3);
                Boolean boolA7 = reVar3.a(15);
                boolA7.getClass();
                String strD23 = reVar3.d(16);
                strD23.getClass();
                String strD24 = reVar3.d(17);
                Integer numValueOf19 = Integer.valueOf((int) ky0.d(strD24, reVar3, 18));
                Double dB3 = reVar3.b();
                dB3.getClass();
                Long lC11 = reVar3.c(20);
                lC11.getClass();
                Integer numValueOf20 = Integer.valueOf((int) lC11.longValue());
                Long lC12 = reVar3.c(21);
                Long lM7 = ky0.m(lC12, reVar3, 22);
                Boolean boolA8 = reVar3.a(23);
                Boolean boolL5 = ky0.l(boolA8, reVar3, 24);
                Boolean boolA9 = reVar3.a(25);
                Boolean boolL6 = ky0.l(boolA9, reVar3, 26);
                Integer numValueOf21 = Integer.valueOf((int) ky0.c(reVar3, 27));
                Object objN11 = ky0.n(reVar3, 28, wfcVar3);
                Object objN12 = ky0.n(reVar3, 29, wfcVar3);
                Long lC13 = reVar3.c(30);
                Long lM8 = ky0.m(lC13, reVar3, 31);
                Long lC14 = reVar3.c(32);
                Long lM9 = ky0.m(lC14, reVar3, 33);
                Long lC15 = reVar3.c(34);
                lC15.getClass();
                Object[] objArr3 = {strO3, objN9, objM3, strD18, numValueOf15, numValueOf16, objW3, strD20, strQ5, strD21, strQ6, strD22, numValueOf17, numValueOf18, objN10, boolA7, strD23, strD24, numValueOf19, dB3, numValueOf20, lC12, lM7, boolA8, boolL5, boolA9, boolL6, numValueOf21, objN11, objN12, lC13, lM8, lC14, lM9, lC15};
                if (objArr3.length != 35) {
                    gp.l("Expected 35 arguments");
                    return null;
                }
                String str19 = (String) objArr3[0];
                Map map11 = (Map) objArr3[1];
                Map map12 = (Map) objArr3[2];
                String str20 = (String) objArr3[3];
                int iIntValue15 = ((Number) objArr3[4]).intValue();
                int iIntValue16 = ((Number) objArr3[5]).intValue();
                List list3 = (List) objArr3[6];
                String str21 = (String) objArr3[7];
                String str22 = (String) objArr3[8];
                String str23 = (String) objArr3[9];
                String str24 = (String) objArr3[10];
                String str25 = (String) objArr3[11];
                int iIntValue17 = ((Number) objArr3[12]).intValue();
                int iIntValue18 = ((Number) objArr3[13]).intValue();
                Map map13 = (Map) objArr3[14];
                boolean zBooleanValue11 = ((Boolean) objArr3[15]).booleanValue();
                String str26 = (String) objArr3[16];
                String str27 = (String) objArr3[17];
                int iIntValue19 = ((Number) objArr3[18]).intValue();
                double dDoubleValue3 = ((Number) objArr3[19]).doubleValue();
                int iIntValue20 = ((Number) objArr3[20]).intValue();
                long jLongValue15 = ((Number) objArr3[21]).longValue();
                long jLongValue16 = ((Number) objArr3[22]).longValue();
                boolean zBooleanValue12 = ((Boolean) objArr3[23]).booleanValue();
                boolean zBooleanValue13 = ((Boolean) objArr3[24]).booleanValue();
                boolean zBooleanValue14 = ((Boolean) objArr3[25]).booleanValue();
                boolean zBooleanValue15 = ((Boolean) objArr3[26]).booleanValue();
                int iIntValue21 = ((Number) objArr3[27]).intValue();
                Map map14 = (Map) objArr3[28];
                Map map15 = (Map) objArr3[29];
                long jLongValue17 = ((Number) objArr3[30]).longValue();
                long jLongValue18 = ((Number) objArr3[31]).longValue();
                long jLongValue19 = ((Number) objArr3[32]).longValue();
                long jLongValue20 = ((Number) objArr3[33]).longValue();
                long jLongValue21 = ((Number) objArr3[34]).longValue();
                str19.getClass();
                map11.getClass();
                map12.getClass();
                str20.getClass();
                list3.getClass();
                str21.getClass();
                str22.getClass();
                str23.getClass();
                str24.getClass();
                map13.getClass();
                str26.getClass();
                str27.getClass();
                map14.getClass();
                map15.getClass();
                return new a82(dDoubleValue3, iIntValue15, iIntValue16, iIntValue17, iIntValue18, iIntValue19, iIntValue20, iIntValue21, jLongValue15, jLongValue16, jLongValue17, jLongValue18, jLongValue19, jLongValue20, jLongValue21, str19, str20, str21, str22, str23, str24, str25, str26, str27, list3, map11, map12, map13, map14, map15, zBooleanValue11, zBooleanValue12, zBooleanValue13, zBooleanValue14, zBooleanValue15);
            case 3:
                v82 v82Var = v82.a;
                re reVar4 = (re) obj;
                String strO4 = ky0.o(reVar4, 0);
                b92 b92Var4 = this.b;
                ((bv4) b92Var4.c).getClass();
                wfc wfcVar4 = wfc.t;
                Object objN13 = ky0.n(reVar4, 1, wfcVar4);
                ((bv4) b92Var4.c).getClass();
                String strD25 = reVar4.d(2);
                strD25.getClass();
                Object objM4 = wfcVar4.m(strD25);
                String strD26 = reVar4.d(3);
                Integer numValueOf22 = Integer.valueOf((int) ky0.d(strD26, reVar4, 4));
                Integer numValueOf23 = Integer.valueOf((int) ky0.c(reVar4, 5));
                fu6 fu6Var4 = fu6.C;
                String strD27 = reVar4.d(6);
                strD27.getClass();
                Object objW4 = fu6Var4.w(strD27);
                String strD28 = reVar4.d(7);
                String strQ7 = ky0.q(strD28, reVar4, 8);
                String strD29 = reVar4.d(9);
                String strQ8 = ky0.q(strD29, reVar4, 10);
                String strD30 = reVar4.d(11);
                Integer numValueOf24 = Integer.valueOf((int) ky0.c(reVar4, 12));
                Integer numValueOf25 = Integer.valueOf((int) ky0.c(reVar4, 13));
                Object objN14 = ky0.n(reVar4, 14, wfcVar4);
                Boolean boolA10 = reVar4.a(15);
                boolA10.getClass();
                String strD31 = reVar4.d(16);
                strD31.getClass();
                String strD32 = reVar4.d(17);
                Integer numValueOf26 = Integer.valueOf((int) ky0.d(strD32, reVar4, 18));
                Double dB4 = reVar4.b();
                dB4.getClass();
                Long lC16 = reVar4.c(20);
                lC16.getClass();
                Integer numValueOf27 = Integer.valueOf((int) lC16.longValue());
                Long lC17 = reVar4.c(21);
                Long lM10 = ky0.m(lC17, reVar4, 22);
                Boolean boolA11 = reVar4.a(23);
                Boolean boolL7 = ky0.l(boolA11, reVar4, 24);
                Boolean boolA12 = reVar4.a(25);
                Boolean boolL8 = ky0.l(boolA12, reVar4, 26);
                Integer numValueOf28 = Integer.valueOf((int) ky0.c(reVar4, 27));
                Object objN15 = ky0.n(reVar4, 28, wfcVar4);
                Object objN16 = ky0.n(reVar4, 29, wfcVar4);
                Long lC18 = reVar4.c(30);
                Long lM11 = ky0.m(lC18, reVar4, 31);
                Long lC19 = reVar4.c(32);
                Long lM12 = ky0.m(lC19, reVar4, 33);
                Long lC20 = reVar4.c(34);
                lC20.getClass();
                Object[] objArr4 = {strO4, objN13, objM4, strD26, numValueOf22, numValueOf23, objW4, strD28, strQ7, strD29, strQ8, strD30, numValueOf24, numValueOf25, objN14, boolA10, strD31, strD32, numValueOf26, dB4, numValueOf27, lC17, lM10, boolA11, boolL7, boolA12, boolL8, numValueOf28, objN15, objN16, lC18, lM11, lC19, lM12, lC20};
                if (objArr4.length != 35) {
                    gp.l("Expected 35 arguments");
                    return null;
                }
                String str28 = (String) objArr4[0];
                Map map16 = (Map) objArr4[1];
                Map map17 = (Map) objArr4[2];
                String str29 = (String) objArr4[3];
                int iIntValue22 = ((Number) objArr4[4]).intValue();
                int iIntValue23 = ((Number) objArr4[5]).intValue();
                List list4 = (List) objArr4[6];
                String str30 = (String) objArr4[7];
                String str31 = (String) objArr4[8];
                String str32 = (String) objArr4[9];
                String str33 = (String) objArr4[10];
                String str34 = (String) objArr4[11];
                int iIntValue24 = ((Number) objArr4[12]).intValue();
                int iIntValue25 = ((Number) objArr4[13]).intValue();
                Map map18 = (Map) objArr4[14];
                boolean zBooleanValue16 = ((Boolean) objArr4[15]).booleanValue();
                String str35 = (String) objArr4[16];
                String str36 = (String) objArr4[17];
                int iIntValue26 = ((Number) objArr4[18]).intValue();
                double dDoubleValue4 = ((Number) objArr4[19]).doubleValue();
                int iIntValue27 = ((Number) objArr4[20]).intValue();
                long jLongValue22 = ((Number) objArr4[21]).longValue();
                long jLongValue23 = ((Number) objArr4[22]).longValue();
                boolean zBooleanValue17 = ((Boolean) objArr4[23]).booleanValue();
                boolean zBooleanValue18 = ((Boolean) objArr4[24]).booleanValue();
                boolean zBooleanValue19 = ((Boolean) objArr4[25]).booleanValue();
                boolean zBooleanValue20 = ((Boolean) objArr4[26]).booleanValue();
                int iIntValue28 = ((Number) objArr4[27]).intValue();
                Map map19 = (Map) objArr4[28];
                Map map20 = (Map) objArr4[29];
                long jLongValue24 = ((Number) objArr4[30]).longValue();
                long jLongValue25 = ((Number) objArr4[31]).longValue();
                long jLongValue26 = ((Number) objArr4[32]).longValue();
                long jLongValue27 = ((Number) objArr4[33]).longValue();
                long jLongValue28 = ((Number) objArr4[34]).longValue();
                str28.getClass();
                map16.getClass();
                map17.getClass();
                str29.getClass();
                list4.getClass();
                str30.getClass();
                str31.getClass();
                str32.getClass();
                str33.getClass();
                map18.getClass();
                str35.getClass();
                str36.getClass();
                map19.getClass();
                map20.getClass();
                return new a82(dDoubleValue4, iIntValue22, iIntValue23, iIntValue24, iIntValue25, iIntValue26, iIntValue27, iIntValue28, jLongValue22, jLongValue23, jLongValue24, jLongValue25, jLongValue26, jLongValue27, jLongValue28, str28, str29, str30, str31, str32, str33, str34, str35, str36, list4, map16, map17, map18, map19, map20, zBooleanValue16, zBooleanValue17, zBooleanValue18, zBooleanValue19, zBooleanValue20);
            case 4:
                return a(obj);
            case 5:
                return b(obj);
            case 6:
                return d(obj);
            case 7:
                return f(obj);
            case 8:
                return i(obj);
            case 9:
                re reVar5 = (re) obj;
                reVar5.getClass();
                ((bv4) this.b.c).getClass();
                return (Map) ky0.n(reVar5, 0, wfc.t);
            case 10:
                return l(obj);
            case 11:
                return m(obj);
            default:
                s82 s82Var = s82.a;
                re reVar6 = (re) obj;
                String strO5 = ky0.o(reVar6, 0);
                bv4 bv4Var = (bv4) this.b.c;
                bv4Var.getClass();
                wfc wfcVar5 = wfc.t;
                String strD33 = reVar6.d(1);
                strD33.getClass();
                Object objM5 = wfcVar5.m(strD33);
                bv4Var.getClass();
                Object objN17 = ky0.n(reVar6, 2, wfcVar5);
                String strD34 = reVar6.d(3);
                Integer numValueOf29 = Integer.valueOf((int) ky0.d(strD34, reVar6, 4));
                Integer numValueOf30 = Integer.valueOf((int) ky0.c(reVar6, 5));
                fu6 fu6Var5 = fu6.C;
                String strD35 = reVar6.d(6);
                strD35.getClass();
                Object objW5 = fu6Var5.w(strD35);
                String strD36 = reVar6.d(7);
                String strQ9 = ky0.q(strD36, reVar6, 8);
                String strD37 = reVar6.d(9);
                String strQ10 = ky0.q(strD37, reVar6, 10);
                String strD38 = reVar6.d(11);
                Integer numValueOf31 = Integer.valueOf((int) ky0.c(reVar6, 12));
                Integer numValueOf32 = Integer.valueOf((int) ky0.c(reVar6, 13));
                Object objN18 = ky0.n(reVar6, 14, wfcVar5);
                Boolean boolA13 = reVar6.a(15);
                boolA13.getClass();
                String strD39 = reVar6.d(16);
                strD39.getClass();
                String strD40 = reVar6.d(17);
                Integer numValueOf33 = Integer.valueOf((int) ky0.d(strD40, reVar6, 18));
                Double dB5 = reVar6.b();
                dB5.getClass();
                Long lC21 = reVar6.c(20);
                lC21.getClass();
                Integer numValueOf34 = Integer.valueOf((int) lC21.longValue());
                Long lC22 = reVar6.c(21);
                Long lM13 = ky0.m(lC22, reVar6, 22);
                Boolean boolA14 = reVar6.a(23);
                Boolean boolL9 = ky0.l(boolA14, reVar6, 24);
                Boolean boolA15 = reVar6.a(25);
                Boolean boolL10 = ky0.l(boolA15, reVar6, 26);
                Integer numValueOf35 = Integer.valueOf((int) ky0.c(reVar6, 27));
                Object objN19 = ky0.n(reVar6, 28, wfcVar5);
                Object objN20 = ky0.n(reVar6, 29, wfcVar5);
                Long lC23 = reVar6.c(30);
                Long lM14 = ky0.m(lC23, reVar6, 31);
                Long lC24 = reVar6.c(32);
                Long lM15 = ky0.m(lC24, reVar6, 33);
                Long lC25 = reVar6.c(34);
                lC25.getClass();
                Object[] objArr5 = {strO5, objM5, objN17, strD34, numValueOf29, numValueOf30, objW5, strD36, strQ9, strD37, strQ10, strD38, numValueOf31, numValueOf32, objN18, boolA13, strD39, strD40, numValueOf33, dB5, numValueOf34, lC22, lM13, boolA14, boolL9, boolA15, boolL10, numValueOf35, objN19, objN20, lC23, lM14, lC24, lM15, lC25};
                if (objArr5.length != 35) {
                    gp.l("Expected 35 arguments");
                    return null;
                }
                String str37 = (String) objArr5[0];
                Map map21 = (Map) objArr5[1];
                Map map22 = (Map) objArr5[2];
                String str38 = (String) objArr5[3];
                int iIntValue29 = ((Number) objArr5[4]).intValue();
                int iIntValue30 = ((Number) objArr5[5]).intValue();
                List list5 = (List) objArr5[6];
                String str39 = (String) objArr5[7];
                String str40 = (String) objArr5[8];
                String str41 = (String) objArr5[9];
                String str42 = (String) objArr5[10];
                String str43 = (String) objArr5[11];
                int iIntValue31 = ((Number) objArr5[12]).intValue();
                int iIntValue32 = ((Number) objArr5[13]).intValue();
                Map map23 = (Map) objArr5[14];
                boolean zBooleanValue21 = ((Boolean) objArr5[15]).booleanValue();
                String str44 = (String) objArr5[16];
                String str45 = (String) objArr5[17];
                int iIntValue33 = ((Number) objArr5[18]).intValue();
                double dDoubleValue5 = ((Number) objArr5[19]).doubleValue();
                int iIntValue34 = ((Number) objArr5[20]).intValue();
                long jLongValue29 = ((Number) objArr5[21]).longValue();
                long jLongValue30 = ((Number) objArr5[22]).longValue();
                boolean zBooleanValue22 = ((Boolean) objArr5[23]).booleanValue();
                boolean zBooleanValue23 = ((Boolean) objArr5[24]).booleanValue();
                boolean zBooleanValue24 = ((Boolean) objArr5[25]).booleanValue();
                boolean zBooleanValue25 = ((Boolean) objArr5[26]).booleanValue();
                int iIntValue35 = ((Number) objArr5[27]).intValue();
                Map map24 = (Map) objArr5[28];
                Map map25 = (Map) objArr5[29];
                long jLongValue31 = ((Number) objArr5[30]).longValue();
                long jLongValue32 = ((Number) objArr5[31]).longValue();
                long jLongValue33 = ((Number) objArr5[32]).longValue();
                long jLongValue34 = ((Number) objArr5[33]).longValue();
                long jLongValue35 = ((Number) objArr5[34]).longValue();
                str37.getClass();
                map21.getClass();
                map22.getClass();
                str38.getClass();
                list5.getClass();
                str39.getClass();
                str40.getClass();
                str41.getClass();
                str42.getClass();
                map23.getClass();
                str44.getClass();
                str45.getClass();
                map24.getClass();
                map25.getClass();
                return new a82(dDoubleValue5, iIntValue29, iIntValue30, iIntValue31, iIntValue32, iIntValue33, iIntValue34, iIntValue35, jLongValue29, jLongValue30, jLongValue31, jLongValue32, jLongValue33, jLongValue34, jLongValue35, str37, str38, str39, str40, str41, str42, str43, str44, str45, list5, map21, map22, map23, map24, map25, zBooleanValue21, zBooleanValue22, zBooleanValue23, zBooleanValue24, zBooleanValue25);
        }
    }
}
