package defpackage;

/* JADX INFO: compiled from: r8-map-id-6d4a6fea4a678d318bae670e8b98ae0a8798384e7d56dd89fbb5b2340ff4b0eb */
/* JADX INFO: loaded from: D:\Tool\vbook-ext\.tools\vbook-dex\classes3.dex */
public final /* synthetic */ class hu9 implements ib4 {
    public final /* synthetic */ int a;

    public /* synthetic */ hu9(int i) {
        this.a = i;
    }

    private final Object a() {
        return new pv9("string:home_search_filer_only_has_result", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18287L, 69L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15143L, 61L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16149L, 61L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23603L, 85L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 17569L, 57L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15747L, 61L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16211L, 65L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 25127L, 81L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14717L, 53L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15491L, 61L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16631L, 57L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15939L, 61L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15577L, 61L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15171L, 53L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15591L, 61L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21243L, 81L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24555L, 77L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14943L, 57L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21207L, 73L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13155L, 53L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13011L, 53L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 24413L, 61L)}));
    }

    private final Object b() {
        return new pv9("string:next_chapter", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22505L, 52L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18605L, 44L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19755L, 48L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28777L, 64L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20775L, 36L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19253L, 48L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19873L, 44L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30609L, 64L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17955L, 40L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18973L, 48L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20357L, 48L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19541L, 40L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 19003L, 44L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18657L, 48L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 19041L, 44L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 26021L, 60L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 30037L, 48L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18313L, 40L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25969L, 64L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16097L, 32L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15965L, 32L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29334L, 48L)}));
    }

    private final Object d() {
        return new pv9("string:go_link", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18089L, 43L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14977L, 35L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16003L, 35L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23357L, 59L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 17427L, 27L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15597L, 31L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16049L, 31L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24889L, 55L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14575L, 31L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15341L, 27L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16453L, 39L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15773L, 35L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15419L, 35L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15005L, 31L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15441L, 27L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21001L, 51L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24333L, 43L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14773L, 51L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20965L, 63L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13017L, 31L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12869L, 31L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 24251L, 35L)}));
    }

    private final Object f() {
        return new pv9("string:no_have_new_chapter", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22587L, 87L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18675L, 79L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19825L, 91L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28875L, 139L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20833L, 87L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19327L, 95L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19943L, 87L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30703L, 147L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 18025L, 67L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 19043L, 91L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20427L, 91L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19603L, 67L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 19073L, 79L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18727L, 83L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 19111L, 91L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 26111L, 99L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 30119L, 123L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18379L, 75L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 26059L, 107L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16155L, 55L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16023L, 63L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29404L, 83L)}));
    }

    private final Object i() {
        return new pv9("string:notification_complete_text", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23074L, 102L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19110L, 98L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 20315L, 102L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 29478L, 146L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 21387L, 98L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19762L, 102L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 20354L, 106L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 31342L, 162L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 18479L, 82L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 19462L, 98L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20882L, 118L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19982L, 102L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 19571L, 98L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19142L, 102L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 19534L, 98L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 26606L, 126L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 30714L, 146L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18758L, 94L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 26606L, 150L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16498L, 82L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16374L, 82L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30002L, 102L)}));
    }

    private final Object l() {
        return new pv9("string:nsfw_filter_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23751L, 56L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19683L, 60L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 20916L, 60L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30267L, 80L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 21928L, 52L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20335L, 56L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21019L, 60L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32335L, 92L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19004L, 56L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20051L, 52L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21571L, 56L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20607L, 68L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20140L, 48L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19739L, 56L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20083L, 56L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27379L, 84L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 31743L, 80L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19327L, 56L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27451L, 84L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16987L, 56L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16859L, 48L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30615L, 72L)}));
    }

    private final Object m() {
        return new pv9("string:off", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23829L, 27L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19765L, 23L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 20998L, 15L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30369L, 35L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22002L, 15L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20413L, 27L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21101L, 27L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32449L, 23L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19082L, 23L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20125L, 23L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21649L, 19L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20697L, 19L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20210L, 15L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19817L, 23L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20161L, 23L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27485L, 23L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 31845L, 23L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19405L, 23L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27557L, 35L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17065L, 19L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16929L, 19L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30709L, 19L)}));
    }

    private final Object n() {
        return new pv9("string:ok", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23857L, 26L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19789L, 14L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21014L, 14L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30405L, 14L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22018L, 14L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20441L, 22L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21129L, 14L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32473L, 34L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19106L, 14L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20149L, 14L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21669L, 14L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20717L, 18L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20226L, 14L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19841L, 14L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20185L, 14L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27509L, 18L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 31869L, 26L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19429L, 18L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27593L, 18L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17085L, 18L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16949L, 18L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30729L, 14L)}));
    }

    private final Object o() {
        return new pv9("string:old_password", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23884L, 68L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19804L, 36L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21029L, 40L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30420L, 56L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22033L, 36L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20464L, 48L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21144L, 48L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32508L, 76L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19121L, 40L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20164L, 44L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21684L, 52L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20736L, 48L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20241L, 40L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19856L, 36L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20200L, 36L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27528L, 56L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 31896L, 68L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19448L, 36L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27612L, 56L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17104L, 32L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16968L, 32L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30744L, 44L)}));
    }

    private final Object p() {
        return new pv9("string:on", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23985L, 26L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19869L, 22L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21098L, 14L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30521L, 26L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22098L, 14L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20545L, 22L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21221L, 22L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32617L, 26L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19190L, 18L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20237L, 18L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21765L, 18L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20817L, 18L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20306L, 14L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19917L, 22L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20269L, 18L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27621L, 18L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32029L, 26L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19517L, 18L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27701L, 34L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17165L, 18L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17029L, 18L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30817L, 18L)}));
    }

    private final Object q() {
        return new pv9("string:ongoing", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 23953L, 31L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19841L, 27L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21070L, 27L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30477L, 43L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22070L, 27L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20513L, 31L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21193L, 27L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32585L, 31L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19162L, 27L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20209L, 27L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21737L, 27L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20785L, 31L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20282L, 23L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19893L, 23L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20237L, 31L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27585L, 35L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 31965L, 63L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19485L, 31L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27669L, 31L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17137L, 27L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17001L, 27L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30789L, 27L)}));
    }

    private final Object r() {
        return new pv9("string:origin", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24012L, 30L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19892L, 26L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21113L, 26L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30548L, 30L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22113L, 26L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20568L, 26L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21244L, 26L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32644L, 26L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19209L, 22L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20256L, 26L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21784L, 22L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20836L, 22L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20321L, 26L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19940L, 26L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20288L, 26L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27640L, 38L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32056L, 42L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19536L, 26L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27736L, 38L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17184L, 22L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17048L, 22L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30836L, 22L)}));
    }

    private final Object s() {
        return new pv9("string:other", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24043L, 25L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19919L, 21L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21140L, 21L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30579L, 25L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22140L, 21L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20595L, 21L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21271L, 21L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32671L, 29L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19232L, 25L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20283L, 21L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21807L, 25L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20859L, 21L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20348L, 21L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19967L, 21L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20315L, 21L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27679L, 29L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32099L, 37L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19563L, 21L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27775L, 25L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17207L, 21L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17071L, 21L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30859L, 21L)}));
    }

    private final Object t() {
        return new pv9("string:page_source", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24069L, 47L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19941L, 43L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21162L, 35L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30605L, 51L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22162L, 35L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20617L, 39L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21293L, 35L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32701L, 55L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19258L, 39L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20305L, 39L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21833L, 43L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20881L, 43L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20370L, 35L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 19989L, 43L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20337L, 43L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27709L, 63L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32137L, 75L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19585L, 35L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27801L, 63L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17229L, 35L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17093L, 35L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30881L, 39L)}));
    }

    private final Object u() {
        return new pv9("string:paragraph_spacing", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24117L, 61L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 19985L, 53L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21198L, 45L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30657L, 77L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22198L, 49L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20657L, 53L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21329L, 61L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32757L, 77L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19298L, 45L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20345L, 53L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21877L, 41L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20925L, 45L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20406L, 45L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 20033L, 49L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20381L, 65L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27773L, 65L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32213L, 85L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19621L, 53L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27865L, 81L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17265L, 33L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17129L, 33L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30921L, 45L)}));
    }

    private final Object v() {
        return new pv9("string:password", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24179L, 44L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 20039L, 24L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21244L, 28L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30735L, 60L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22248L, 28L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20711L, 32L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21391L, 32L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32835L, 44L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19344L, 32L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20399L, 28L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21919L, 36L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 20971L, 32L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20452L, 32L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 20083L, 24L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20447L, 24L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27839L, 32L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32299L, 48L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19675L, 24L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27947L, 32L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17299L, 24L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17163L, 24L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30967L, 32L)}));
    }

    private final Object w() {
        return new pv9("string:no_lookup_found", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22675L, 91L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18755L, 91L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19917L, 67L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 29015L, 107L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 21009L, 55L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19423L, 91L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 20031L, 67L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30851L, 111L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 18093L, 79L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 19135L, 75L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20519L, 79L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19671L, 79L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 19153L, 59L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18811L, 75L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 19203L, 79L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 26211L, 99L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 30243L, 103L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18455L, 63L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 26167L, 103L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16211L, 63L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 16087L, 63L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29564L, 103L)}));
    }

    private final Object x() {
        return new pv9("string:percent", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24224L, 23L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 20064L, 23L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21273L, 23L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30796L, 23L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22277L, 23L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20744L, 23L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21424L, 23L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32880L, 23L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19377L, 23L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20428L, 23L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21956L, 23L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 21004L, 23L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20485L, 23L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 20108L, 23L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20472L, 23L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27872L, 23L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32348L, 23L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19700L, 23L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 27980L, 23L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17324L, 23L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17188L, 23L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31000L, 23L)}));
    }

    private final Object y() {
        return new pv9("string:picker_image", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24248L, 48L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 20088L, 40L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21297L, 44L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30820L, 60L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22301L, 36L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20768L, 40L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21448L, 44L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32904L, 64L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19401L, 36L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20452L, 44L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 21980L, 40L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 21028L, 44L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20509L, 44L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 20132L, 40L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20496L, 44L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27896L, 72L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32372L, 64L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19724L, 36L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 28004L, 68L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17348L, 36L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17212L, 36L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31024L, 36L)}));
    }

    private final Object z() {
        return new pv9("string:prev", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24297L, 28L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 20129L, 28L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21342L, 24L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30881L, 44L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22338L, 24L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20809L, 24L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21493L, 28L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 32969L, 32L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19438L, 28L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20497L, 24L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 22021L, 20L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 21073L, 20L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20554L, 20L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 20173L, 20L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20541L, 24L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27969L, 28L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32437L, 44L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19761L, 24L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 28073L, 28L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17385L, 24L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17249L, 24L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31061L, 24L)}));
    }

    @Override // defpackage.ib4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pv9("string:minute", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22208L, 30L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18384L, 22L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19522L, 22L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28432L, 30L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20562L, 22L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19008L, 22L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19632L, 22L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30256L, 30L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17734L, 22L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18740L, 22L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20128L, 18L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19324L, 18L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18794L, 22L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18436L, 22L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18792L, 22L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25688L, 30L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29644L, 30L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18096L, 22L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25640L, 34L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15900L, 22L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15772L, 22L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29055L, 22L)}));
            case 1:
                return new pv9("string:month", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22239L, 21L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18407L, 25L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19545L, 21L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28463L, 29L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20585L, 21L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19031L, 17L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19655L, 21L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30287L, 33L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17757L, 21L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18763L, 21L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20147L, 17L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19343L, 21L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18817L, 21L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18459L, 25L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18815L, 21L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25719L, 29L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29675L, 33L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18119L, 17L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25675L, 29L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15923L, 17L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15795L, 17L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29078L, 21L)}));
            case 2:
                return new pv9("string:more_setting", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22261L, 68L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18433L, 44L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19567L, 48L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28493L, 80L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20607L, 40L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19049L, 48L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19677L, 48L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30321L, 72L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17779L, 44L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18785L, 44L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20165L, 44L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19365L, 40L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18839L, 44L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18485L, 44L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18837L, 48L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25749L, 84L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29709L, 96L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18137L, 40L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25705L, 80L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15941L, 36L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15813L, 36L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29100L, 44L)}));
            case 3:
                return new pv9("string:name_manager", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22330L, 68L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18478L, 48L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19616L, 56L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28574L, 100L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20648L, 52L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19098L, 68L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19726L, 56L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30394L, 88L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17824L, 44L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18830L, 56L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20210L, 44L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19406L, 48L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18884L, 36L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18530L, 48L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18886L, 76L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25834L, 80L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29806L, 84L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18178L, 56L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25786L, 76L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15978L, 44L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15850L, 40L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29145L, 48L)}));
            case 4:
                return new pv9("string:ner_analyzer", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22399L, 36L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18527L, 40L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19673L, 40L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28675L, 48L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20701L, 36L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19167L, 40L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19783L, 40L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30483L, 60L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17869L, 44L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18887L, 44L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20255L, 48L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19455L, 40L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18921L, 36L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18579L, 40L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18963L, 40L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25915L, 52L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29891L, 76L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18235L, 40L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25863L, 52L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16023L, 40L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15891L, 40L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29194L, 40L)}));
            case 5:
                return new pv9("string:ner_skip_list", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29235L, 53L)));
            case 6:
                return new pv9("string:new_password", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22436L, 68L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18568L, 36L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19714L, 40L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28724L, 52L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20738L, 36L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19208L, 44L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19824L, 48L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30544L, 64L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17914L, 40L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18932L, 40L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20304L, 52L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19496L, 44L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18958L, 44L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18620L, 36L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 19004L, 36L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25968L, 52L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29968L, 68L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18276L, 36L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25916L, 52L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16064L, 32L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15932L, 32L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29289L, 44L)}));
            case 7:
                return new pv9("string:next", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22558L, 28L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18650L, 24L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19804L, 20L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28842L, 32L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20812L, 20L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19302L, 24L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19918L, 24L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30674L, 28L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17996L, 28L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 19022L, 20L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20406L, 20L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19582L, 20L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 19048L, 24L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18706L, 20L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 19086L, 24L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 26082L, 28L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 30086L, 32L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18354L, 24L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 26034L, 24L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16130L, 24L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15998L, 24L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29383L, 20L)}));
            case 8:
                return b();
            case 9:
                return d();
            case 10:
                return a();
            case 11:
                return f();
            case 12:
                return l();
            case 13:
                return new pv9("string:no_have_new_episode", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20921L, 87L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 29488L, 75L)}));
            case 14:
                return m();
            case 15:
                return n();
            case 16:
                return o();
            case 17:
                return p();
            case 18:
                return q();
            case 19:
                return r();
            case 20:
                return s();
            case 21:
                return t();
            case 22:
                return i();
            case 23:
                return u();
            case 24:
                return v();
            case 25:
                return w();
            case 26:
                return x();
            case 27:
                return y();
            case 28:
                return z();
            default:
                return new pv9("string:priv", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 24326L, 20L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 20158L, 24L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 21367L, 20L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 30926L, 36L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22363L, 24L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 20834L, 24L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 21522L, 20L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 33002L, 28L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 19467L, 24L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 20522L, 24L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 22042L, 36L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 21094L, 20L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 20575L, 24L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 20194L, 24L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 20566L, 24L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 27998L, 28L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 32482L, 40L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 19786L, 20L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 28102L, 36L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 17410L, 20L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 17274L, 20L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31086L, 20L)}));
        }
    }
}
