package defpackage;

/* JADX INFO: compiled from: r8-map-id-6d4a6fea4a678d318bae670e8b98ae0a8798384e7d56dd89fbb5b2340ff4b0eb */
/* JADX INFO: loaded from: D:\Tool\vbook-ext\.tools\vbook-dex\classes3.dex */
public final /* synthetic */ class qu9 implements ib4 {
    public final /* synthetic */ int a;

    public /* synthetic */ qu9(int i) {
        this.a = i;
    }

    private final Object a() {
        return new pv9("string:setting_restore_mode_replace_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 37620L, 181L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 30992L, 97L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 32508L, 117L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 47204L, 241L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 32914L, 109L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 31952L, 129L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 33240L, 149L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 49736L, 177L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 29880L, 109L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 31372L, 113L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 32772L, 133L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 31788L, 133L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 31220L, 121L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 31212L, 105L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 31772L, 121L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 43232L, 169L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 49460L, 201L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 30476L, 109L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 43340L, 149L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 26604L, 97L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 26460L, 97L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 44052L, 129L)}));
    }

    private final Object b() {
        return new pv9("string:setting_sync_backup_extension", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39086L, 61L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32006L, 57L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33590L, 57L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49022L, 65L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33924L, 53L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33098L, 53L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34462L, 53L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51394L, 73L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30930L, 49L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32422L, 53L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34042L, 53L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32938L, 57L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32326L, 49L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32278L, 53L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32890L, 53L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44702L, 65L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51218L, 69L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31582L, 53L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44746L, 65L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27562L, 53L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27426L, 45L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45275L, 69L)}));
    }

    private final Object d() {
        return new pv9("string:setting_sync_backup_extension_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38987L, 98L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31931L, 74L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33511L, 78L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48903L, 118L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33841L, 82L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33027L, 70L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34371L, 90L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51283L, 110L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30851L, 78L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32355L, 66L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33967L, 74L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32863L, 74L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32255L, 70L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32191L, 86L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32803L, 86L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44603L, 98L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51091L, 126L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31495L, 86L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44647L, 98L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27499L, 62L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27355L, 70L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45188L, 86L)}));
    }

    private final Object f() {
        return new pv9("string:setting_sync_backup_import", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39264L, 78L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32144L, 50L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33728L, 58L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49232L, 82L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34050L, 50L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33252L, 54L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34612L, 62L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51592L, 70L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31052L, 50L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32552L, 50L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34204L, 70L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33080L, 66L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32460L, 62L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32412L, 54L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33024L, 54L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44888L, 70L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51400L, 82L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31716L, 54L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44928L, 66L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27680L, 50L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27540L, 50L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45421L, 58L)}));
    }

    private final Object i() {
        return new pv9("string:setting_statistic", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 37962L, 53L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31210L, 41L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 32738L, 41L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 47646L, 53L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33144L, 41L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32206L, 45L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 33514L, 41L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 50098L, 49L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30114L, 37L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 31614L, 41L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33018L, 33L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32042L, 33L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 31462L, 41L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 31442L, 41L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32018L, 45L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 43558L, 53L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 49874L, 45L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 30710L, 45L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 43654L, 53L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 26830L, 33L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 26670L, 33L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 44330L, 41L)}));
    }

    private final Object l() {
        return new pv9("string:setting_sync_backup_import_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39148L, 115L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32064L, 79L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33648L, 79L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49088L, 143L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33978L, 71L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33152L, 99L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34516L, 95L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51468L, 123L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30980L, 71L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32476L, 75L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34096L, 107L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32996L, 83L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32376L, 83L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32332L, 79L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32944L, 79L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44768L, 119L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51288L, 111L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31636L, 79L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44812L, 115L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27616L, 63L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27472L, 67L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45345L, 75L)}));
    }

    private final Object m() {
        return new pv9("string:setting_sync_backup_last", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39343L, 72L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32195L, 56L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33787L, 52L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49315L, 108L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34101L, 48L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33307L, 68L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34675L, 60L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51663L, 76L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31103L, 56L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32603L, 52L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34275L, 64L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33147L, 52L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32523L, 52L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32467L, 64L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33079L, 52L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44959L, 96L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51483L, 76L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31771L, 52L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44995L, 104L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27731L, 48L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27591L, 48L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45480L, 60L)}));
    }

    private final Object n() {
        return new pv9("string:setting_reader_turn_page_volume", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 36703L, 123L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 30303L, 107L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 31807L, 99L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 46123L, 143L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 32321L, 79L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 31263L, 87L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 32463L, 103L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 48531L, 207L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 29207L, 95L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 30723L, 87L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 32083L, 79L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 31099L, 83L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 30519L, 99L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 30567L, 99L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 31067L, 95L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 42187L, 163L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 48295L, 151L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 29767L, 99L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 42371L, 163L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 26055L, 67L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 25911L, 67L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 43311L, 99L)}));
    }

    private final Object o() {
        return new pv9("string:setting_sync_backup_setting", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39537L, 59L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32349L, 51L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33945L, 55L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49581L, 59L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34247L, 47L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33493L, 55L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34849L, 51L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51909L, 67L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31257L, 51L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32765L, 51L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34421L, 43L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33285L, 43L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32669L, 51L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32641L, 51L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33241L, 55L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45197L, 59L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51745L, 75L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31921L, 47L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45257L, 67L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27861L, 43L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27721L, 43L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45642L, 51L)}));
    }

    private final Object p() {
        return new pv9("string:setting_sync_backup_setting_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39416L, 120L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32252L, 96L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33840L, 104L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49424L, 156L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34150L, 96L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33376L, 116L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34736L, 112L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51740L, 168L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31160L, 96L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32656L, 108L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34340L, 80L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33200L, 84L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32576L, 92L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32532L, 108L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33132L, 108L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45056L, 140L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51560L, 184L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31824L, 96L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45100L, 156L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27780L, 80L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27640L, 80L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45541L, 100L)}));
    }

    private final Object q() {
        return new pv9("string:setting_sync_backup_shelf", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39704L, 53L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32480L, 41L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34092L, 53L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49764L, 69L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34374L, 41L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33636L, 49L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35004L, 53L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52116L, 65L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31392L, 49L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32900L, 45L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34552L, 41L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33412L, 41L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32812L, 49L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32772L, 45L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33380L, 45L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45360L, 49L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51996L, 77L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32052L, 45L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45444L, 49L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27976L, 41L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27844L, 41L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45793L, 53L)}));
    }

    private final Object r() {
        return new pv9("string:setting_sync_backup_shelf_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39597L, 106L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32401L, 78L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34001L, 90L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49641L, 122L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34295L, 78L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33549L, 86L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34901L, 102L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51977L, 138L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31309L, 82L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32817L, 82L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34465L, 86L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33329L, 82L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32721L, 90L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32693L, 78L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33297L, 82L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45257L, 102L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51821L, 174L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31969L, 82L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45325L, 118L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27905L, 70L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27765L, 78L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45694L, 98L)}));
    }

    private final Object s() {
        return new pv9("string:setting_sync_backup_status", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39758L, 50L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32522L, 42L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34146L, 42L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49834L, 58L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34416L, 42L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33686L, 42L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35058L, 42L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52182L, 58L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31442L, 42L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32946L, 42L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34594L, 54L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33454L, 42L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32862L, 42L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32818L, 42L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33426L, 42L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45410L, 50L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52074L, 54L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32098L, 42L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45494L, 50L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28018L, 42L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27886L, 42L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45847L, 54L)}));
    }

    private final Object t() {
        return new pv9("string:setting_sync_backup_storage", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39809L, 71L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32565L, 63L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34189L, 67L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49893L, 87L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34459L, 51L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33729L, 71L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35101L, 71L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52241L, 71L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31485L, 63L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32989L, 71L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34649L, 51L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33497L, 59L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32905L, 63L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32861L, 63L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33469L, 71L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45461L, 87L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52129L, 83L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32141L, 67L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45545L, 87L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28061L, 51L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27929L, 51L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45902L, 75L)}));
    }

    private final Object u() {
        return new pv9("string:setting_sync_backup_sync", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39881L, 92L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32629L, 60L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34257L, 76L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49981L, 104L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34511L, 60L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33801L, 68L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35173L, 76L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52313L, 100L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31549L, 60L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33061L, 64L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34701L, 96L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33557L, 84L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32969L, 76L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32925L, 64L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33541L, 68L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45549L, 88L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52213L, 108L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32209L, 72L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45633L, 88L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28113L, 60L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27981L, 60L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45978L, 68L)}));
    }

    private final Object v() {
        return new pv9("string:setting_sync_backup_type", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39974L, 68L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32690L, 60L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34334L, 64L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50086L, 96L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34572L, 48L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33870L, 72L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35250L, 68L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52414L, 80L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31610L, 60L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33126L, 64L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34798L, 48L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33642L, 56L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33046L, 60L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32990L, 60L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33610L, 72L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45638L, 96L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52322L, 92L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32282L, 64L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45722L, 84L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28174L, 48L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28042L, 48L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 46047L, 64L)}));
    }

    private final Object w() {
        return new pv9("string:setting_sync_failed", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40135L, 99L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32811L, 79L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34459L, 103L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50299L, 159L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34669L, 75L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34019L, 87L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35387L, 111L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52563L, 131L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31731L, 83L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33255L, 111L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 34911L, 95L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33751L, 99L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33167L, 103L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33123L, 91L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33743L, 75L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45843L, 131L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52511L, 139L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32411L, 87L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45923L, 135L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28271L, 63L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28139L, 63L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 46219L, 91L)}));
    }

    private final Object x() {
        return new pv9("string:setting_report", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 37063L, 42L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 30603L, 42L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 32067L, 34L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 46551L, 42L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 32561L, 34L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 31543L, 38L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 32759L, 38L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 49047L, 66L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 29491L, 38L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 30983L, 34L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 32335L, 50L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 31351L, 34L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 30783L, 34L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 30851L, 30L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 31355L, 34L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 42591L, 58L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 48795L, 62L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 30055L, 42L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 42803L, 38L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 26267L, 30L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 26123L, 30L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 43619L, 38L)}));
    }

    private final Object y() {
        return new pv9("string:setting_sync_in_progress", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40235L, 48L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32891L, 48L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34563L, 48L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50459L, 48L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 34745L, 48L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34107L, 48L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35499L, 48L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52695L, 48L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31815L, 48L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33367L, 48L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35007L, 48L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33851L, 48L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33271L, 48L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33215L, 48L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33819L, 48L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45975L, 48L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52651L, 48L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32499L, 48L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46059L, 48L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28335L, 48L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28203L, 48L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 46311L, 48L)}));
    }

    @Override // defpackage.ib4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pv9("string:setting_display_color", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 29276L, 49L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 24148L, 37L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 25580L, 37L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 36804L, 45L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 26482L, 37L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 24872L, 37L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 25756L, 41L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 39208L, 41L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 23328L, 37L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 24596L, 37L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 26104L, 33L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 25120L, 37L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 24628L, 37L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 24296L, 37L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 24632L, 33L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 33528L, 41L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 38844L, 37L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 23712L, 37L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 33688L, 45L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 20912L, 37L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 20760L, 37L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 36308L, 45L)}));
            case 1:
                return new pv9("string:setting_reader_turn_page_group_interaction", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 32164L, 78L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 43134L, 82L)}));
            case 2:
                return new pv9("string:setting_sync_backup_clear_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38251L, 134L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31439L, 86L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 32987L, 82L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48003L, 198L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33377L, 74L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32459L, 86L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 33767L, 98L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 50471L, 114L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30347L, 90L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 31855L, 78L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33271L, 114L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32295L, 98L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 31719L, 90L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 31683L, 86L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32267L, 90L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 43875L, 110L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 50255L, 130L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 30975L, 78L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 43939L, 106L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27043L, 74L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 26891L, 74L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 44644L, 94L)}));
            case 3:
                return new pv9("string:setting_reader_turn_page_keyboard", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 36573L, 129L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 30205L, 97L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 31721L, 85L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 45985L, 137L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 32243L, 77L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 31173L, 89L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 32365L, 97L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 48353L, 177L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 29113L, 93L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 30637L, 85L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 31997L, 85L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 31013L, 85L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 30421L, 97L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 30481L, 85L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 30981L, 85L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 42037L, 149L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 48141L, 153L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 29677L, 89L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 42217L, 153L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 25989L, 65L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 25845L, 65L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 43217L, 93L)}));
            case 4:
                return new pv9("string:setting_sync_backup_content_download", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38602L, 100L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31662L, 64L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33218L, 76L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48466L, 92L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33584L, 68L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32722L, 72L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34042L, 72L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 50830L, 120L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30586L, 72L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32078L, 72L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33578L, 96L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32546L, 80L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 31962L, 68L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 31910L, 64L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32518L, 68L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44198L, 96L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 50634L, 136L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31202L, 68L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44254L, 92L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27250L, 64L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27102L, 64L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 44899L, 72L)}));
            case 5:
                return new pv9("string:setting_sync_backup_content_download_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38488L, 113L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31592L, 69L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33136L, 81L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48344L, 121L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33510L, 73L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32628L, 93L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 33948L, 93L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 50680L, 149L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30500L, 85L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32000L, 77L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33468L, 109L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32460L, 85L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 31880L, 81L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 31840L, 69L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32424L, 93L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44084L, 113L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 50472L, 161L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31116L, 85L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44136L, 117L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27176L, 73L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27024L, 77L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 44809L, 89L)}));
            case 6:
                return new pv9("string:setting_sync_backup_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38703L, 108L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31727L, 72L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33295L, 80L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48559L, 128L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33653L, 68L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32795L, 80L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34115L, 100L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 50951L, 108L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30659L, 68L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32151L, 76L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33675L, 108L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32627L, 88L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32031L, 80L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 31975L, 76L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32587L, 76L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44295L, 120L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 50771L, 120L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31271L, 84L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44347L, 112L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27315L, 68L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27167L, 68L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 44972L, 84L)}));
            case 7:
                return new pv9("string:setting_sync_backup_export", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38916L, 70L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31880L, 50L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33452L, 58L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48824L, 78L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33790L, 50L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32972L, 54L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34308L, 62L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51200L, 82L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30800L, 50L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32304L, 50L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33892L, 74L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32796L, 66L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32192L, 62L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32136L, 54L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32748L, 54L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44532L, 70L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 51008L, 82L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31436L, 58L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44576L, 70L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27448L, 50L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27304L, 50L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45129L, 58L)}));
            case 8:
                return new pv9("string:setting_sync_backup_export_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 38812L, 103L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 31800L, 79L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 33376L, 75L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 48688L, 135L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 33722L, 67L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 32876L, 95L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 34216L, 91L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 51060L, 139L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 30728L, 71L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 32228L, 75L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 33784L, 107L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 32716L, 79L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 32112L, 79L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 32052L, 83L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 32664L, 83L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 44416L, 115L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 50892L, 115L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 31356L, 79L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 44460L, 115L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 27384L, 63L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 27236L, 67L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 45057L, 71L)}));
            case 9:
                return b();
            case 10:
                return d();
            case 11:
                return f();
            case 12:
                return a();
            case 13:
                return l();
            case 14:
                return m();
            case 15:
                return n();
            case 16:
                return o();
            case 17:
                return p();
            case 18:
                return q();
            case 19:
                return r();
            case 20:
                return s();
            case 21:
                return t();
            case 22:
                return u();
            case 23:
                return i();
            case 24:
                return v();
            case 25:
                return new pv9("string:setting_sync_configure", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 46172L, 46L)));
            case 26:
                return w();
            case 27:
                return x();
            case 28:
                return y();
            default:
                return new pv9("string:setting_sync_not_configured", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 46360L, 59L)));
        }
    }
}
