package defpackage;

import android.content.Context;
import android.os.Build;
import java.lang.annotation.Annotation;
import java.util.UUID;
import org.mozilla.javascript.Parser;

/* JADX INFO: compiled from: r8-map-id-6d4a6fea4a678d318bae670e8b98ae0a8798384e7d56dd89fbb5b2340ff4b0eb */
/* JADX INFO: loaded from: D:\Tool\vbook-ext\.tools\vbook-dex\classes3.dex */
public final /* synthetic */ class s5 implements ib4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new hv9("string-array:community_tabs", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 10L, 175L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10L, 119L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10L, 115L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 10L, 195L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10L, 99L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10L, 115L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10L, 127L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 10L, 243L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10L, 103L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10L, 111L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10L, 119L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10L, 107L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10L, 107L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10L, 127L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10L, 127L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 10L, 207L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 10L, 219L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10L, 119L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 10L, 215L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 10L, 91L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 10L, 83L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10L, 123L)}));
    }

    private final Object b() {
        return new hv9("string-array:shelf_tabs", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3089L, 121L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2661L, 85L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2681L, 77L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3765L, 137L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2513L, 73L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2737L, 97L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2737L, 97L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3929L, 157L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2537L, 77L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2737L, 85L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2517L, 81L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2613L, 77L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2637L, 77L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2745L, 89L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2745L, 93L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3537L, 113L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3825L, 161L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2609L, 97L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3581L, 113L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2337L, 77L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2297L, 77L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2761L, 109L)}));
    }

    private final Object d() {
        return new hv9("string-array:split_chapter_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3211L, 190L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2747L, 162L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2759L, 150L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3903L, 242L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2587L, 126L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2835L, 162L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2835L, 162L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4087L, 306L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2615L, 178L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2823L, 154L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2599L, 106L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2691L, 130L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2715L, 170L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2835L, 170L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2839L, 158L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3651L, 202L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3987L, 262L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2707L, 170L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3695L, 230L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2415L, 110L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2375L, 106L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2871L, 146L)}));
    }

    private final Object f() {
        return new hv9("string-array:table_of_content_tabs", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3402L, 96L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2910L, 56L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2910L, 76L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4146L, 124L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2714L, 72L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2998L, 64L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2998L, 76L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4394L, 104L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2794L, 60L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2978L, 60L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2706L, 68L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2822L, 56L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2886L, 72L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3006L, 64L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2998L, 64L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3854L, 88L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4250L, 96L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2878L, 68L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3926L, 76L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2526L, 52L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2482L, 52L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3018L, 68L)}));
    }

    private final Object i() {
        return new hv9("string-array:text_scroll_type", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3499L, 151L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2967L, 139L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2987L, 139L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4271L, 223L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2787L, 127L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3063L, 151L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3075L, 147L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4499L, 267L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2855L, 123L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3039L, 147L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2775L, 183L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2879L, 159L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2959L, 139L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3071L, 147L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3063L, 143L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3943L, 243L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4347L, 227L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2947L, 123L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 4003L, 235L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2579L, 107L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2535L, 107L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3087L, 127L)}));
    }

    private final Object l() {
        return new hv9("string-array:translate_qt_break_segment_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3651L, 104L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 3107L, 84L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 3127L, 76L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4495L, 116L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2915L, 80L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3215L, 80L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3223L, 84L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4767L, 156L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2979L, 80L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3187L, 80L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2959L, 76L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 3039L, 88L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 3099L, 76L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3219L, 92L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3207L, 80L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 4187L, 116L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4575L, 124L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 3071L, 88L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 4239L, 104L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2687L, 72L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2643L, 68L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3215L, 84L)}));
    }

    private final Object m() {
        return new hv9("string-array:translate_qt_luat_nhan_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3756L, 113L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 3192L, 117L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 3204L, 141L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4612L, 209L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2996L, 121L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3296L, 133L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3308L, 129L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4924L, 145L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 3060L, 113L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3268L, 133L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 3036L, 113L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 3128L, 113L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 3176L, 145L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3312L, 121L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3288L, 133L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 4304L, 161L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4700L, 125L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 3160L, 117L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 4344L, 145L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2760L, 105L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2712L, 93L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3300L, 105L)}));
    }

    private final Object n() {
        return new hv9("string-array:extension_types", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 294L, 98L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 238L, 86L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 246L, 90L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 374L, 82L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 210L, 82L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 254L, 86L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 262L, 86L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 418L, 82L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 202L, 82L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 238L, 90L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 222L, 82L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 226L, 82L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 246L, 82L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 278L, 86L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 266L, 82L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 358L, 138L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 386L, 82L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 234L, 82L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 394L, 138L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 190L, 78L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 186L, 78L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 254L, 82L)}));
    }

    @Override // defpackage.ib4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return Integer.valueOf(vb8.a.i(2147418112) + Parser.ARGC_LIMIT);
            case 1:
                return UUID.randomUUID().toString();
            case 2:
                return new qa7("com.reader.app.ui.screen.community.AddConversationRoute", u6.INSTANCE, new Annotation[0]);
            case 3:
                return j39.g(7, null, 0L);
            case 4:
                throw new IllegalStateException("Alert not initialized");
            case 5:
                return new pb(g23.b);
            case 6:
                String str = Build.VERSION.RELEASE;
                return str == null ? "" : str;
            case 7:
                return Integer.valueOf(Build.VERSION.SDK_INT);
            case 8:
                return new e0b(-3.4028235E38f, 0.0f, 0.0f);
            case 9:
                fn1 fn1Var = gs.a;
                return jj2.a;
            case 10:
                fn1 fn1Var2 = gs.a;
                return wk2.a;
            case 11:
                return pu1.w("app_config");
            case 12:
                return pu1.w("app_settings");
            case 13:
                Context context = kl8.D;
                context.getClass();
                return new wb(context);
            case 14:
                return new hv9("string-array:setting_reader_scroll_type_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2284L, 72L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 1940L, 76L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 1964L, 72L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 2668L, 80L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 1852L, 64L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 1976L, 72L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 1988L, 76L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 2732L, 100L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 1880L, 64L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 1988L, 72L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 1888L, 84L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 1884L, 76L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 1916L, 68L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2012L, 80L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2000L, 68L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2544L, 88L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 2752L, 84L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 1944L, 72L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2588L, 88L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 1764L, 64L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1724L, 64L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2024L, 64L)}));
            case 15:
                return new hv9("string-array:setting_reader_touch_turn_page_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2357L, 158L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2017L, 150L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2037L, 146L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 2749L, 282L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 1917L, 150L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2049L, 154L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2065L, 150L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 2833L, 282L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 1945L, 142L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2061L, 174L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 1973L, 146L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 1961L, 154L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 1985L, 146L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2093L, 146L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2069L, 146L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2633L, 246L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 2837L, 238L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2017L, 138L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2677L, 226L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 1829L, 118L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1789L, 126L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2089L, 150L)}));
            case 16:
                return new hv9("string-array:download_range_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 186L, 107L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 130L, 107L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 126L, 119L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 206L, 167L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 110L, 99L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 126L, 127L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 138L, 123L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 254L, 163L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 114L, 87L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 122L, 115L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 130L, 91L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 118L, 107L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 118L, 127L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 138L, 139L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 138L, 127L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 218L, 139L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 230L, 155L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 130L, 103L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 226L, 167L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 102L, 87L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 94L, 91L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 134L, 119L)}));
            case 17:
                return new hv9("string-array:setting_reader_translate_detect_language_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2516L, 183L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2168L, 167L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2184L, 167L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3032L, 263L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2068L, 135L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2204L, 179L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2216L, 179L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3116L, 275L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2088L, 147L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2236L, 167L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2120L, 135L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2116L, 139L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2132L, 171L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2240L, 159L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2216L, 175L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2880L, 223L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3076L, 323L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2156L, 147L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2904L, 235L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 1948L, 127L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1916L, 119L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2240L, 191L)}));
            case 18:
                return new hv9("string-array:setting_swipe_back_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2700L, 138L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2336L, 90L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2352L, 90L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3296L, 138L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2204L, 94L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2384L, 98L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2396L, 94L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3392L, 182L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2236L, 86L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2404L, 102L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2256L, 74L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2256L, 138L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2304L, 94L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2400L, 106L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2392L, 102L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3104L, 122L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3400L, 122L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2304L, 86L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3140L, 122L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2076L, 70L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2036L, 70L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2432L, 98L)}));
            case 19:
                return new hv9("string-array:setting_sync_backup_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2839L, 78L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2427L, 78L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2443L, 78L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3435L, 78L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2299L, 78L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2483L, 78L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2491L, 78L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3575L, 78L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2323L, 78L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2507L, 78L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2331L, 78L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2395L, 78L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2399L, 78L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2507L, 78L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2495L, 78L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3227L, 78L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3523L, 78L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2391L, 78L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3263L, 78L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2147L, 78L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2107L, 78L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2531L, 78L)}));
            case 20:
                return new hv9("string-array:shelf_sort_by_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2918L, 170L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2506L, 154L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2522L, 158L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3514L, 250L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2378L, 134L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2562L, 174L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2570L, 166L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3654L, 274L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2402L, 134L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2586L, 150L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2410L, 106L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2474L, 138L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2478L, 158L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2586L, 158L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2574L, 170L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3306L, 230L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3602L, 222L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2470L, 138L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3342L, 238L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2226L, 110L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2186L, 110L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2610L, 150L)}));
            case 21:
                return b();
            case 22:
                return d();
            case 23:
                return f();
            case 24:
                return a();
            case 25:
                return i();
            case 26:
                return l();
            case 27:
                return m();
            case 28:
                return n();
            default:
                return new hv9("string-array:translate_qt_name_vp_values", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3870L, 66L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 3310L, 66L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 3346L, 66L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4822L, 66L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 3118L, 66L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3430L, 66L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3438L, 66L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 5070L, 66L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 3174L, 66L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3402L, 66L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 3150L, 66L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 3242L, 66L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 3322L, 66L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3434L, 66L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3422L, 66L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 4466L, 66L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4826L, 66L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 3278L, 66L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 4490L, 66L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2866L, 66L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2806L, 66L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3406L, 66L)}));
        }
    }
}
