package defpackage;

/* JADX INFO: compiled from: r8-map-id-6d4a6fea4a678d318bae670e8b98ae0a8798384e7d56dd89fbb5b2340ff4b0eb */
/* JADX INFO: loaded from: D:\Tool\vbook-ext\.tools\vbook-dex\classes3.dex */
public final /* synthetic */ class ut9 implements ib4 {
    public final /* synthetic */ int a;

    public /* synthetic */ ut9(int i) {
        this.a = i;
    }

    @Override // defpackage.ib4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pv9("string:community_conversation_group", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9411L, 44L)));
            case 1:
                return new pv9("string:community_conversation_list", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9456L, 63L)));
            case 2:
                return new pv9("string:community_conversation_search", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9520L, 73L)));
            case 3:
                return new pv9("string:community_create_group_chat", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9594L, 59L)));
            case 4:
                return new pv9("string:community_delete", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 8239L, 32L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9891L, 32L)}));
            case 5:
                return new pv9("string:community_delete_post_message", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 8046L, 93L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9654L, 109L)}));
            case 6:
                return new pv9("string:community_delete_post_title", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 8140L, 51L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9764L, 59L)}));
            case 7:
                return new pv9("string:community_deleted_post", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 8192L, 46L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9824L, 66L)}));
            case 8:
                return new pv9("string:community_global_chat", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 9276L, 57L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 7848L, 45L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 8240L, 53L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 11620L, 73L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 8272L, 45L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 8172L, 45L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 8476L, 49L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 12420L, 73L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 7516L, 41L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 8104L, 49L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 8076L, 53L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 7804L, 49L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 8040L, 49L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 7964L, 45L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 8092L, 45L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 10648L, 53L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 12172L, 65L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 7564L, 45L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 10780L, 65L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 6788L, 45L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 6732L, 45L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9924L, 45L)}));
            case 9:
                return new pv9("string:add_emoji_album_failed", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 4995L, 102L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 4267L, 86L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 4411L, 106L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 6263L, 134L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 4019L, 78L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 4431L, 78L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 4475L, 102L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 6627L, 130L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 4131L, 86L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 4415L, 110L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 4159L, 98L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 4215L, 98L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 4323L, 102L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 4391L, 86L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 4407L, 78L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 5783L, 126L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 6411L, 142L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 4203L, 70L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 5819L, 130L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 3719L, 70L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 3659L, 70L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 4395L, 78L)}));
            case 10:
                return new pv9("string:add_to_download_failed", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 5688L, 138L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 4828L, 118L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 5028L, 166L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 7104L, 218L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 4520L, 114L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 4988L, 134L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 5092L, 150L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 7548L, 222L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 4668L, 138L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 4988L, 142L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 4788L, 178L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 4808L, 162L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 4900L, 142L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 4936L, 122L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 4956L, 138L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 6584L, 182L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 7304L, 242L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 4688L, 110L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 6584L, 182L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 4204L, 106L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 4132L, 110L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 4984L, 138L)}));
            case 11:
                return new pv9("string:community_group_add_member", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 9970L, 58L)));
            case 12:
                return new pv9("string:community_group_public_list", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 9334L, 67L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 7894L, 59L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 8294L, 67L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 11694L, 75L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 8675L, 55L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 8218L, 59L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 8526L, 55L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 12494L, 91L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 7558L, 51L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 8154L, 55L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 8130L, 59L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 7854L, 55L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 8090L, 59L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 8010L, 55L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 8138L, 59L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 10702L, 79L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 12238L, 83L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 7610L, 67L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 10846L, 71L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 6834L, 51L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 6778L, 51L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11525L, 59L)}));
            case 13:
                return new pv9("string:community_group_change_cover", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10029L, 60L)));
            case 14:
                return new pv9("string:community_group_public_list_empty", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11447L, 77L)));
            case 15:
                return new pv9("string:community_group_public_list_empty_description", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11317L, 129L)));
            case 16:
                return new pv9("string:community_group_public_search", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11585L, 65L)));
            case 17:
                return new pv9("string:community_group_role_admin", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11698L, 58L)));
            case 18:
                return new pv9("string:community_group_role_member", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11757L, 51L)));
            case 19:
                return new pv9("string:community_group_role_owner", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11809L, 50L)));
            case 20:
                return new pv9("string:community_group_selected_count", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11860L, 78L)));
            case 21:
                return new pv9("string:community_group_system_add_member", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12021L, 85L)));
            case 22:
                return new pv9("string:community_group_leave", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10972L, 45L)));
            case 23:
                return new pv9("string:community_group_system_add_member_preview", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11939L, 81L)));
            case 24:
                return new pv9("string:community_group_system_join", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12179L, 67L)));
            case 25:
                return new pv9("string:community_group_cover_optional", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10090L, 78L)));
            case 26:
                return new pv9("string:community_group_system_join_preview", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12107L, 71L)));
            case 27:
                return new pv9("string:community_group_system_kick_member", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12334L, 110L)));
            case 28:
                return new pv9("string:community_group_system_kick_member_preview", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12247L, 86L)));
            default:
                return new pv9("string:community_group_system_leave", e11.d0(new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12514L, 64L)));
        }
    }
}
