package defpackage;

/* JADX INFO: compiled from: r8-map-id-6d4a6fea4a678d318bae670e8b98ae0a8798384e7d56dd89fbb5b2340ff4b0eb */
/* JADX INFO: loaded from: D:\Tool\vbook-ext\.tools\vbook-dex\classes3.dex */
public final /* synthetic */ class yu9 implements ib4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new pv9("string:translate_qt_import_success", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47685L, 103L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38937L, 87L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40857L, 91L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59149L, 147L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41994L, 83L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40353L, 87L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41853L, 91L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62193L, 107L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37497L, 71L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39525L, 87L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41337L, 107L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39925L, 103L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39337L, 95L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39365L, 87L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39957L, 87L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54189L, 115L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61781L, 127L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38557L, 99L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54301L, 115L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33413L, 71L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33241L, 71L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55078L, 87L)}));
    }

    private final Object b() {
        return new pv9("string:translate_qt_longest_word", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47789L, 61L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39025L, 57L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40949L, 57L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59297L, 77L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42078L, 53L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40441L, 57L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41945L, 69L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62301L, 101L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37569L, 57L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39613L, 57L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41445L, 57L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40029L, 57L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39433L, 57L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39453L, 57L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40045L, 57L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54305L, 81L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61909L, 93L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38657L, 53L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54417L, 69L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33485L, 49L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33313L, 49L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55166L, 65L)}));
    }

    private final Object d() {
        return new pv9("string:translate_qt_lookup", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47992L, 79L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39204L, 71L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41128L, 55L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59572L, 95L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42237L, 51L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40608L, 75L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42128L, 63L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62552L, 79L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37720L, 55L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39788L, 63L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41604L, 55L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40204L, 55L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39588L, 47L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39624L, 67L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40224L, 75L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54540L, 83L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62164L, 99L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38820L, 55L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54648L, 83L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33632L, 51L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33440L, 51L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55349L, 63L)}));
    }

    private final Object f() {
        return new pv9("string:translate_qt_lookup_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47851L, 140L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39083L, 120L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41007L, 120L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59375L, 196L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42132L, 104L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40499L, 108L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42015L, 112L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62403L, 148L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37627L, 92L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39671L, 116L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41503L, 100L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40087L, 116L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39491L, 96L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39511L, 112L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40103L, 120L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54387L, 152L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62003L, 160L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38711L, 108L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54487L, 160L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33535L, 96L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33363L, 76L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55232L, 116L)}));
    }

    private final Object i() {
        return new pv9("string:translate_qt_luat_nhan", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48072L, 58L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39276L, 58L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41184L, 58L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59668L, 90L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42289L, 58L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40684L, 62L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42192L, 58L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62632L, 66L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37776L, 54L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39852L, 66L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41660L, 50L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40260L, 50L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39636L, 62L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39692L, 54L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40300L, 62L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54624L, 74L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62264L, 74L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38876L, 54L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54732L, 74L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33684L, 46L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33492L, 46L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55413L, 46L)}));
    }

    private final Object l() {
        return new pv9("string:translate_qt_name_vp", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48233L, 72L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39433L, 72L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41361L, 76L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59945L, 96L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42458L, 72L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40845L, 72L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42357L, 72L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62885L, 112L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37933L, 64L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 40017L, 68L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41817L, 64L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40421L, 60L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39809L, 72L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39849L, 68L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40469L, 72L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54853L, 88L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62581L, 128L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 39041L, 68L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54933L, 88L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33837L, 60L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33641L, 60L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55578L, 72L)}));
    }

    private final Object m() {
        return new pv9("string:translate_qt_name_vp_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48131L, 101L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39335L, 97L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41243L, 117L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59759L, 185L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42348L, 109L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40747L, 97L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42251L, 105L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62699L, 185L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37831L, 101L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39919L, 97L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41711L, 105L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40311L, 109L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39699L, 109L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39747L, 101L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40363L, 105L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54699L, 153L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62339L, 241L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38931L, 109L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54807L, 125L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33731L, 105L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33539L, 101L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55460L, 117L)}));
    }

    private final Object n() {
        return new pv9("string:translate_qt_other_dictionary_title", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48306L, 83L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39506L, 71L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41438L, 83L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 60042L, 95L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42531L, 71L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40918L, 83L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42430L, 79L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62998L, 103L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37998L, 71L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 40086L, 75L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41882L, 59L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40482L, 63L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39882L, 71L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39918L, 75L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40542L, 83L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54942L, 91L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62710L, 107L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 39110L, 67L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 55022L, 103L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33898L, 59L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33702L, 59L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55651L, 67L)}));
    }

    private final Object o() {
        return new pv9("string:translate_qt_personal_general", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48561L, 105L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39717L, 93L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41685L, 101L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 60333L, 141L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42734L, 89L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 41137L, 89L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42653L, 93L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 63333L, 157L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 38205L, 77L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 40281L, 89L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 42069L, 85L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40681L, 77L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 40089L, 93L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 40133L, 89L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40765L, 89L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 55217L, 121L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 63181L, 177L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 39301L, 81L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 55309L, 145L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 34089L, 73L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33889L, 81L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55886L, 89L)}));
    }

    private final Object p() {
        return new pv9("string:translate_qt_personal_general_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48390L, 170L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39578L, 138L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41522L, 162L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 60138L, 194L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42603L, 130L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 41002L, 134L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42510L, 142L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 63102L, 230L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 38070L, 134L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 40162L, 118L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41942L, 126L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40546L, 134L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39954L, 134L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39994L, 138L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40626L, 138L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 55034L, 182L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 62818L, 362L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 39178L, 122L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 55126L, 182L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33958L, 130L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33762L, 126L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55719L, 166L)}));
    }

    private final Object q() {
        return new pv9("string:translate_qt_priv_dictionary_title", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48667L, 78L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39811L, 66L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41787L, 74L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 60475L, 82L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42824L, 66L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 41227L, 70L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42747L, 70L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 63491L, 90L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 38283L, 62L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 40371L, 66L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 42155L, 58L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40759L, 62L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 40183L, 70L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 40223L, 66L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40855L, 70L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 55339L, 78L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 63359L, 106L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 39383L, 62L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 55455L, 86L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 34163L, 58L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33971L, 58L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55976L, 70L)}));
    }

    private final Object r() {
        return new pv9("string:tts_background_music_empty", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50257L, 110L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41141L, 78L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43161L, 102L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62461L, 130L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44030L, 62L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42609L, 86L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44157L, 66L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65569L, 134L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39545L, 70L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41709L, 62L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43421L, 82L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42021L, 78L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41449L, 70L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41585L, 74L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42253L, 74L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57217L, 90L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65477L, 122L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40677L, 86L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57305L, 98L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35265L, 66L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35077L, 66L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57398L, 98L)}));
    }

    private final Object s() {
        return new pv9("string:translate_qt_secondary_dictionary_title", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 48746L, 87L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 39878L, 75L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 41862L, 79L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 60558L, 91L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 42891L, 75L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 41298L, 79L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 42818L, 79L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 63582L, 111L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 38346L, 67L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 40438L, 75L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 42214L, 63L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 40822L, 67L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 40254L, 75L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 40290L, 75L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 40926L, 79L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 55418L, 107L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 63466L, 95L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 39446L, 71L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 55542L, 95L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 34222L, 63L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 34030L, 63L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56047L, 71L)}));
    }

    private final Object t() {
        return new pv9("string:tts_background_music_manager", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50368L, 88L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41220L, 68L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43264L, 72L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62592L, 116L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44093L, 68L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42696L, 72L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44224L, 76L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65704L, 124L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39616L, 60L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41772L, 76L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43504L, 48L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42100L, 64L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41520L, 72L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41660L, 72L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42328L, 72L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57308L, 104L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65600L, 108L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40764L, 76L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57404L, 100L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35332L, 60L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35144L, 60L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57497L, 68L)}));
    }

    private final Object u() {
        return new pv9("string:tts_background_music_volume", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50457L, 63L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41289L, 47L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43337L, 55L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62709L, 51L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44162L, 43L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42769L, 47L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44301L, 43L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65829L, 55L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39677L, 43L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41849L, 43L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43553L, 43L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42165L, 43L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41593L, 43L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41733L, 51L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42401L, 43L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57413L, 59L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65709L, 75L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40841L, 51L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57505L, 59L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35393L, 43L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35205L, 43L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57566L, 51L)}));
    }

    private final Object v() {
        return new pv9("string:tts_default", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50586L, 35L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41390L, 31L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43446L, 27L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62834L, 39L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44259L, 27L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42870L, 31L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44394L, 31L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65974L, 43L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39766L, 27L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41950L, 31L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43630L, 35L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42258L, 31L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41690L, 31L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41830L, 27L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42498L, 31L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57538L, 39L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65862L, 35L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40946L, 27L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57630L, 39L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35482L, 27L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35294L, 27L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57663L, 35L)}));
    }

    private final Object w() {
        return new pv9("string:tts_engine", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50622L, 38L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41422L, 26L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43474L, 26L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62874L, 34L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44287L, 26L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42902L, 26L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44426L, 26L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66018L, 34L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39794L, 26L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41982L, 26L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43666L, 34L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42290L, 26L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41722L, 26L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41858L, 26L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42530L, 30L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57578L, 34L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65898L, 42L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40974L, 26L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57670L, 34L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35510L, 26L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35322L, 26L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57699L, 34L)}));
    }

    private final Object x() {
        return new pv9("string:tts_error_content", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50661L, 137L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41449L, 105L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43501L, 125L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62909L, 233L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44314L, 101L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42929L, 129L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44453L, 129L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66053L, 249L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39821L, 101L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42009L, 117L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43701L, 145L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42317L, 141L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41749L, 105L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41885L, 121L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42561L, 133L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57613L, 165L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65941L, 205L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41001L, 113L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57705L, 165L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35537L, 85L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35349L, 85L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57734L, 113L)}));
    }

    @Override // defpackage.ib4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pv9("string:translate_qt_dic_mode_replace", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47165L, 69L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38501L, 57L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40353L, 57L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58517L, 85L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41570L, 53L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 39889L, 57L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41341L, 57L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61529L, 69L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37117L, 53L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39057L, 61L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40805L, 65L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39429L, 61L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38873L, 57L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38893L, 61L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39509L, 57L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53561L, 69L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61045L, 89L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38081L, 65L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53685L, 69L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33029L, 53L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32857L, 53L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54606L, 65L)}));
            case 1:
                return new pv9("string:translate_qt_dic_mode_replace_desc", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47030L, 134L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38394L, 106L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40230L, 122L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58318L, 198L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41443L, 126L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 39766L, 122L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41214L, 126L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61358L, 170L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37010L, 106L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38930L, 126L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40674L, 130L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39306L, 122L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38742L, 130L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38790L, 102L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39394L, 114L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53406L, 154L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 60822L, 222L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37978L, 102L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53522L, 162L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32934L, 94L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32762L, 94L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54475L, 130L)}));
            case 2:
                return new pv9("string:translate_qt_download", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47235L, 89L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38559L, 69L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40411L, 77L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58603L, 101L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41624L, 65L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 39947L, 77L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41399L, 85L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61599L, 133L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37171L, 57L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39119L, 69L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40871L, 73L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39491L, 65L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38931L, 73L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38955L, 65L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39567L, 65L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53631L, 101L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61135L, 133L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38147L, 69L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53755L, 121L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33083L, 53L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32911L, 53L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54672L, 73L)}));
            case 3:
                return new pv9("string:translate_qt_export_failed", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47325L, 86L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38629L, 74L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40489L, 94L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58705L, 106L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41690L, 74L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40025L, 82L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41485L, 98L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61733L, 122L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37229L, 66L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39189L, 86L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40945L, 110L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39557L, 98L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39005L, 82L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39021L, 90L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39633L, 82L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53733L, 126L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61269L, 138L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38217L, 86L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53877L, 110L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33137L, 70L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32965L, 70L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54746L, 86L)}));
            case 4:
                return new pv9("string:translate_qt_export_success", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47412L, 99L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38704L, 87L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40584L, 91L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58812L, 143L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41765L, 83L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40108L, 87L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41584L, 91L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61856L, 119L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37296L, 71L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39276L, 87L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41056L, 111L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39656L, 103L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39088L, 91L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39112L, 91L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39716L, 87L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53860L, 119L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61408L, 127L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38304L, 99L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53988L, 115L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33208L, 71L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33036L, 71L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54833L, 87L)}));
            case 5:
                return new pv9("string:translate_qt_general_dictionary_title", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47512L, 81L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38792L, 69L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40676L, 81L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58956L, 81L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41849L, 69L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40196L, 73L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41676L, 77L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61976L, 105L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37368L, 61L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39364L, 73L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41168L, 61L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39760L, 65L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39180L, 73L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39204L, 69L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39804L, 69L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53980L, 81L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61536L, 105L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38404L, 65L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54104L, 89L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33280L, 61L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33108L, 61L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54921L, 69L)}));
            case 6:
                return new pv9("string:translate_qt_import_failed", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47594L, 90L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38862L, 74L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40758L, 98L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 59038L, 110L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 41919L, 74L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40270L, 82L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41754L, 98L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62082L, 110L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37430L, 66L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39438L, 86L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41230L, 106L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39826L, 98L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39254L, 82L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39274L, 90L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39874L, 82L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54062L, 126L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61642L, 138L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38470L, 86L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54194L, 106L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33342L, 70L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33170L, 70L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 54991L, 86L)}));
            case 7:
                return new pv9("string:stat_listen_time", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 37514L, 44L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50119L, 48L)}));
            case 8:
                return a();
            case 9:
                return new pv9("string:stat_tab_library", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 37886L, 36L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50527L, 40L)}));
            case 10:
                return b();
            case 11:
                return d();
            case 12:
                return f();
            case 13:
                return i();
            case 14:
                return l();
            case 15:
                return m();
            case 16:
                return n();
            case 17:
                return o();
            case 18:
                return p();
            case 19:
                return new pv9("string:stat_no_reading_data", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 37559L, 72L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50168L, 84L)}));
            case 20:
                return new pv9("string:stat_tab_time", fw.Q0(new ql8[]{new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 37923L, 29L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50568L, 37L)}));
            case 21:
                return q();
            case 22:
                return r();
            case 23:
                return s();
            case 24:
                return t();
            case 25:
                return u();
            case 26:
                return v();
            case 27:
                return w();
            case 28:
                return x();
            default:
                return new pv9("string:tts_error_not_install", fw.Q0(new ql8[]{new ql8(dx1.p("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50799L, 153L), new ql8(dx1.p("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41555L, 129L), new ql8(dx1.p("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43627L, 125L), new ql8(dx1.p("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 63143L, 217L), new ql8(dx1.p("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44416L, 121L), new ql8(dx1.p("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43059L, 141L), new ql8(dx1.p("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44583L, 153L), new ql8(dx1.p("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66303L, 245L), new ql8(dx1.p("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39923L, 121L), new ql8(dx1.p("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42127L, 137L), new ql8(dx1.p("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43847L, 177L), new ql8(dx1.p("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42459L, 153L), new ql8(dx1.p("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41855L, 133L), new ql8(dx1.p("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42007L, 137L), new ql8(dx1.p("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42695L, 141L), new ql8(dx1.p("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57779L, 213L), new ql8(dx1.p("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 66147L, 269L), new ql8(dx1.p("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41115L, 125L), new ql8(dx1.p("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57871L, 209L), new ql8(fw.Q0(new qa8[]{new fm5("zh"), new ch8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35623L, 101L), new ql8(dx1.p("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35435L, 97L), new ql8(sc3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57848L, 161L)}));
        }
    }
}
